stages:
- build

build_server:
  stage: build
  image: node:18-alpine
  script:
    - cd ./server
    - npm install
    - npm run build
  artifacts:
    expire_in: "30 days"
    paths:
      - "server/dist"