stages:
- test
- deploy

test_server:
  stage: test
  image: node:18
  script:
    - cd ./server
    - npm install
    - npm test


deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
    - node:18-alpine
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - curl -L https://fly.io/install.sh | sh
  script: 
    - echo ${FLY_API_TOKEN} 
    - /root/.fly/bin/flyctl deploy
