# Start from the node image
FROM node:18

# Expose the port 8080
EXPOSE 8080

# Use /usr/src/app as the workdir. The following instructions will be executed in this location
WORKDIR /usr/src/app

# Copy the the files require to install the dependencies
